# Generated by Django 4.0.4 on 2022-04-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacrecertify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bartoken',
            old_name='bar',
            new_name='bar_id',
        ),
    ]
