# Generated by Django 4.0.4 on 2022-04-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacrecertify', '0002_rename_bar_bartoken_bar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartoken',
            name='bar_id',
            field=models.UUIDField(),
        ),
    ]
