# Generated by Django 4.0.4 on 2022-05-01 23:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('h4tcsacapp', '0001_initial'), ('h4tcsacapp', '0002_alter_bar_city_alter_bar_contact_name_and_more'), ('h4tcsacapp', '0003_favorite'), ('h4tcsacapp', '0003_alter_bar_certification_date_alter_barreport_uid_and_more'), ('h4tcsacapp', '0004_merge_20220429_1649'), ('h4tcsacapp', '0005_remove_listbar_bar_remove_listbar_list_delete_list_and_more'), ('h4tcsacapp', '0005_alter_favorite_uid'), ('h4tcsacapp', '0005_alter_bar_name_alter_bar_phone_number_and_more'), ('h4tcsacapp', '0006_merge_20220429_2025'), ('h4tcsacapp', '0005_barreport_date_submitted'), ('h4tcsacapp', '0007_merge_20220501_1613'), ('h4tcsacapp', '0008_alter_bar_options_alter_barreport_options_and_more')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_safebar', models.BooleanField(blank=True, default=False, verbose_name='Is Safe Bar')),
                ('is_approved', models.BooleanField(blank=True, default=False, verbose_name='Is Approved')),
                ('name', models.CharField(max_length=254, verbose_name='Bar Name')),
                ('contact_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Contact Name')),
                ('phone_number', models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Phone Number')),
                ('street_address', models.CharField(blank=True, default='', max_length=254, verbose_name='Street Address')),
                ('city', models.CharField(blank=True, default='', max_length=254, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, default='', max_length=12, verbose_name='ZIP / Postal code')),
                ('latitude', models.CharField(blank=True, default='', max_length=10, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, default='', max_length=10, verbose_name='Longitude')),
                ('certification_date', models.DateField(blank=True, default=None, null=True, verbose_name='Certification Date')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('image', models.URLField(blank=True, default='', max_length=254, verbose_name='Image')),
                ('description', models.CharField(blank=True, default='', max_length=254, verbose_name='Description')),
                ('website', models.URLField(blank=True, default='', max_length=254, verbose_name='Website')),
            ],
            options={
                'ordering': ['certification_date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Sponser')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.BigIntegerField(verbose_name='Phone Number')),
                ('contact_name', models.CharField(max_length=50, verbose_name='Contact Name')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=254, verbose_name='Question')),
                ('answer', models.CharField(max_length=10000, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('media_url', models.URLField(max_length=254, verbose_name='Media URL')),
                ('is_video', models.BooleanField(verbose_name='Is Video')),
                ('button_text', models.CharField(max_length=254, verbose_name='Button Text')),
                ('link_url', models.CharField(max_length=254, verbose_name='Link URL')),
                ('link_is_external', models.BooleanField(verbose_name='Link is External')),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Report Name')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=254, verbose_name='Desription')),
                ('url', models.URLField(max_length=254, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('logo', models.CharField(max_length=254, verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100, verbose_name='User ID')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='h4tcsacapp.bar')),
            ],
        ),
        migrations.CreateModel(
            name='BarReport',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=254, verbose_name='Comment')),
                ('uid', models.CharField(max_length=100, verbose_name='User ID')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='h4tcsacapp.bar')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='h4tcsacapp.reporttype')),
                ('date_submitted', models.DateTimeField(default=datetime.datetime(2022, 5, 1, 22, 47, 3, 321539), verbose_name='Date Submitted')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_number', models.BigIntegerField(verbose_name='Rating Number')),
                ('comment', models.CharField(max_length=254, verbose_name='Comment')),
                ('uid', models.CharField(max_length=100, verbose_name='User ID')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='h4tcsacapp.bar')),
            ],
        ),
    ]
