# Generated by Django 4.0.4 on 2022-04-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_safebar', models.BooleanField(verbose_name='Is Safe Bar')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('contact_name', models.CharField(max_length=1024, verbose_name='Contact Name')),
                ('phone_number', models.IntegerField(verbose_name='Phone Number')),
                ('street_address', models.CharField(max_length=1024, verbose_name='Street Address')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('latitude', models.CharField(max_length=10, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=10, verbose_name='Longitude')),
                ('certification_date', models.DateField(verbose_name='Certification Date')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('image', models.URLField(verbose_name='Image')),
                ('description', models.CharField(max_length=254, verbose_name='Description')),
                ('website', models.URLField(verbose_name='Website')),
            ],
        ),
    ]
