# Generated by Django 4.0.4 on 2022-04-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
