# Generated by Django 4.0.4 on 2022-04-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='city',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='description',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='image',
            field=models.URLField(blank=True, default='', max_length=254, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Approved'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='is_safebar',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Safe Bar'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='phone_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='website',
            field=models.URLField(blank=True, default='', max_length=254, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='ZIP / Postal code'),
        ),
    ]
