# Generated by Django 4.0.4 on 2022-04-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
    ]
