# Generated by Django 4.0.4 on 2022-04-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0002_bar_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='certification_date',
            field=models.DateField(blank=True, verbose_name='Certification Date'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='is_safebar',
            field=models.BooleanField(default=False, verbose_name='Is Safe Bar'),
        ),
    ]
