# Generated by Django 4.0.4 on 2022-04-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0002_bar_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.BigIntegerField(verbose_name='Phone Number'),
        ),
    ]
