# Generated by Django 4.0.4 on 2022-04-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0002_alter_bars_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bars',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
