# Generated by Django 4.0.4 on 2022-04-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0003_alter_bar_certification_date_alter_bar_is_safebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='image',
            field=models.URLField(blank=True, max_length=254, verbose_name='Image'),
        ),
    ]
