# Generated by Django 4.0.4 on 2022-04-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0003_alter_bars_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bars',
            new_name='Bar',
        ),
    ]
