# Generated by Django 4.0.4 on 2022-04-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0003_alter_bar_certification_date_alter_barreport_uid_and_more'),
        ('h4tcsacapp', '0003_favorite'),
    ]

    operations = [
    ]
