# Generated by Django 4.0.4 on 2022-04-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0004_alter_bar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='certification_date',
            field=models.DateField(null=True, verbose_name='Certification Date'),
        ),
    ]
