# Generated by Django 4.0.4 on 2022-04-29 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0004_merge_20220429_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='barreport',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Submitted'),
            preserve_default=False,
        ),
    ]
