# Generated by Django 4.0.4 on 2022-04-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0004_merge_20220429_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listbar',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='listbar',
            name='list',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='ListBar',
        ),
    ]
