# Generated by Django 4.0.4 on 2022-04-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0004_merge_20220429_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_number',
            field=models.BigIntegerField(verbose_name='Rating Number'),
        ),
    ]
