# Generated by Django 4.0.4 on 2022-04-26 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0004_rename_bars_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Longitude'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_number', models.IntegerField(verbose_name='Rating Number')),
                ('comment', models.CharField(max_length=254, verbose_name='Comment')),
                ('uid', models.CharField(max_length=25, verbose_name='User ID')),
                ('bar_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='h4tcsacapp.bar')),
            ],
        ),
    ]
