# Generated by Django 4.0.4 on 2022-04-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0004_merge_20220429_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='uid',
            field=models.CharField(max_length=100, verbose_name='User ID'),
        ),
    ]
