# Generated by Django 4.0.4 on 2022-04-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0003_alter_contact_phone_number'),
        ('h4tcsacapp', '0005_alter_bar_certification_date'),
    ]

    operations = [
    ]
