# Generated by Django 4.0.4 on 2022-04-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0005_alter_bar_name_alter_bar_phone_number_and_more'),
        ('h4tcsacapp', '0005_alter_favorite_uid'),
        ('h4tcsacapp', '0005_remove_listbar_bar_remove_listbar_list_delete_list_and_more'),
    ]

    operations = [
    ]
