# Generated by Django 4.0.4 on 2022-04-26 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0006_reporttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=254, verbose_name='Comment')),
                ('uid', models.CharField(max_length=25, verbose_name='User ID')),
                ('bar_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='h4tcsacapp.bar')),
                ('report_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='h4tcsacapp.reporttype')),
            ],
        ),
    ]
