# Generated by Django 4.0.4 on 2022-05-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0005_barreport_date_submitted'),
        ('h4tcsacapp', '0006_merge_20220429_2025'),
    ]

    operations = [
    ]
