# Generated by Django 4.0.4 on 2022-05-01 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0007_merge_20220501_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ['certification_date']},
        ),
        migrations.AlterModelOptions(
            name='barreport',
            options={'ordering': ['-date_submitted']},
        ),
        migrations.AddField(
            model_name='barreport',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bar',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Bar Name'),
        ),
        migrations.AlterField(
            model_name='barreport',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 22, 47, 3, 321539), verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Sponser'),
        ),
    ]
