# Generated by Django 4.0.4 on 2022-04-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0007_barreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Desription')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
            ],
        ),
    ]
