# Generated by Django 4.0.4 on 2022-04-29 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0007_alter_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('media_url', models.URLField(max_length=254, verbose_name='Media URL')),
                ('is_video', models.BooleanField(verbose_name='Is Video')),
                ('button_text', models.CharField(max_length=254, verbose_name='Button Text')),
                ('link_url', models.CharField(max_length=254, verbose_name='Link URL')),
                ('link_is_external', models.BooleanField(verbose_name='Link is External')),
            ],
        ),
    ]
