# Generated by Django 4.0.4 on 2022-04-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0008_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
