# Generated by Django 4.0.4 on 2022-05-01 23:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0008_alter_bar_options_alter_barreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barreport',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h4tcsacapp.bar'),
        ),
        migrations.AlterField(
            model_name='barreport',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 23, 38, 24, 855854), verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='barreport',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Is Visible'),
        ),
        migrations.AlterField(
            model_name='barreport',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h4tcsacapp.reporttype'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h4tcsacapp.bar'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h4tcsacapp.bar'),
        ),
    ]
