# Generated by Django 4.0.4 on 2022-04-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0006_merge_20220429_0752'),
        ('h4tcsacapp', '0008_landingcontent'),
    ]

    operations = [
    ]
