# Generated by Django 4.0.4 on 2022-05-01 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0009_alter_barreport_bar_alter_barreport_date_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='is_positive',
            field=models.BooleanField(default=False, verbose_name='Is Positive'),
        ),
        migrations.AlterField(
            model_name='barreport',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 23, 51, 2, 158914), verbose_name='Date Submitted'),
        ),
    ]
