# Generated by Django 4.0.4 on 2022-04-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0009_merge_0006_merge_20220429_0752_0008_landingcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=10000, verbose_name='Answer'),
        ),
    ]
