# Generated by Django 4.0.4 on 2022-05-01 23:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0010_reporttype_is_positive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barreport',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 23, 58, 12, 887761, tzinfo=utc), verbose_name='Date Submitted'),
        ),
    ]
