# Generated by Django 4.0.4 on 2022-04-27 00:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0010_alter_bar_id_alter_barreport_id_alter_rating_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Sponser Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.IntegerField(verbose_name='Phone Number')),
                ('contact_name', models.CharField(max_length=50, verbose_name='Contact Name')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=254, verbose_name='FAQ Question')),
                ('answer', models.CharField(max_length=254, verbose_name='FAQ Answer')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=25, verbose_name='User ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('logo', models.CharField(max_length=254, verbose_name='Logo')),
            ],
        ),
        migrations.RenameField(
            model_name='barreport',
            old_name='bar_id',
            new_name='bar',
        ),
        migrations.RenameField(
            model_name='barreport',
            old_name='report_type_id',
            new_name='report_type',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='bar_id',
            new_name='bar',
        ),
        migrations.AlterField(
            model_name='bar',
            name='city',
            field=models.CharField(max_length=254, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='contact_name',
            field=models.CharField(max_length=255, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='image',
            field=models.URLField(max_length=254, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='street_address',
            field=models.CharField(max_length=254, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='website',
            field=models.URLField(max_length=254, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(max_length=254, verbose_name='Desription'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(max_length=254, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='ListBar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='h4tcsacapp.bar')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='h4tcsacapp.list')),
            ],
        ),
    ]
