# Generated by Django 4.0.4 on 2022-05-02 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0011_alter_barreport_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barreport',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 1, 26, 39, 259847), verbose_name='Date Submitted'),
        ),
    ]
