# Generated by Django 4.0.4 on 2022-05-10 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0012_alter_barreport_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barreport',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 17, 29, 41, 127548), verbose_name='Date Submitted'),
        ),
    ]
