# Generated by Django 4.0.4 on 2022-07-16 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h4tcsacapp', '0013_alter_barreport_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barreport',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 16, 20, 22, 52, 747302), verbose_name='Date Submitted'),
        ),
    ]
